import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar"
import Footer from "@/components/footer/index"
import Wp from "@/components/wp"



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="!scroll-smooth" lang="en">
      <body className="bg-black">
        <main className="font-fontum bg-black">
        <Wp />
          <Navbar />
          {children}
          <Footer />
          </main>
           
      </body>
    </html>
  );
}
